### PR TITLE
use treehouses/rpi-couchdb:1.7.1 for bell (fixes #260)

### LINKED ISSUE #260: update dogi/rpi-couchdb (1.6.1) to treehouses/rpi-couchdb:1.7.1

### PR DESCRIPTION
**Pull request by xyb994**
Fixes #260

### CODE REVIEW

**Comment by sahilph** [comment]
Can you modify it to use **treehouses/couchdb:1.7.1**  to support  the multi architecture ?

**Comment by xyb994** [comment]
@mappuji Yup, already tested on Raspberry Pi and CouchDB is working fine.

@sahilph I might not have the full context here. I thought we are still trying to figure our how to pull the arm version when building the image on travis. https://github.com/treehouses/builder/commits/multiarch is the branch that we are trying to work on, right?

**Comment by mappuji** [comment]
oops, I forget @xyb994 

basically you need to pull from `treehouses/couchdb` instead of `treehouses/rpi-couchdb` because the former will automatically decide which architecture we run the Docker.

**Comment by dogi** [comment]
@sahilph and @mappuji you are right that the long term goal is to go to `treehouses/couchdb`,
anyhow since as I might have explained to some of you that is a complex update
we @xyb994 and decided to do that in 2 steps first https://github.com/treehouses/builder/issues/260
and then https://github.com/treehouses/builder/compare/multiarch

**Comment by mappuji** [comment]
Got it @dogi

**Comment by sahilph** [comment]
Alright @dogi  👍

**Pull request merged**
