### PR TITLE
sl package added (fixes #622)

### LINKED ISSUE #622: add package sl
image

you may have to add enhance the PATH

### PR DESCRIPTION
**Pull request by jamjakpa**
adding sl at the end

### CODE REVIEW

**Comment by jamjakpa** [comment]
@dogi , I added the missing part when you have time please check

**Comment by jamjakpa** [comment]
2020-01-26-050157_1824x984_scrot

image root@treehouses:/home/pi# treehouses image
release-sl1

successfully installed. 
sl command works perfect 
done.

**Comment by jamjakpa** [comment]
I build the new travis release yesterday down below are the infos for reference 

release-sl2 ls_hello
 Commit 8847e3c 
 Compare release-sl2 
 Tag release-sl2 
 avatar jamjakpa
 #2854 passed
 Ran for 34 min 33 sec
 17 hours ago

**Comment by dogi** [comment]
```
root@treehouses:/usr/bin# dpkg -l |grep " sl "
ii  sl                                    5.02-1                              armhf        Correct you if you type `sl' by mistake
root@treehouses:/usr/bin# which sl
root@treehouses:/usr/bin# sl
-bash: sl: command not found
root@treehouses:/usr/bin# /usr/games/sl
```

**Comment by dogi** [comment]
https://travis-ci.org/treehouses/builder#L3711

**Pull request merged**
